src/objects/Analitical_Staging_Object__c.object
<CustomObject>
    <fields>
        <fullName>Access_Level__c</fullName>
        <label>Access Level</label>
        <picklist>
            <picklistValues>
                <fullName>All</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Read</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Edit</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Account_Access_Level__c</fullName>
        <label>Account Access Level</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Read</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Edit</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Case_Access_Level__c</fullName>
        <label>Case Access Level</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Read</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Edit</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact_Access_Level__c</fullName>
        <label>Contact Access Level</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Read</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Edit</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Customer_Id__c</fullName>
        <description>Id of a customer – should match Account  (by external id) linked to opportunity</description>
        <label>Customer Id</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Member_Id__c</fullName>
        <label>Member Id</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_of_Days__c</fullName>
        <label>Number of Days</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity_Lead_Owner__c</fullName>
        <label>Opportunity/Lead Owner</label>
        <length>16</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NOK</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Team_Role__c</fullName>
        <label>Team Role</label>
        <picklist>
            <picklistValues>
                <fullName>Account Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executive Sponsor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Sales Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Support</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Possible values:
•	01 – New Opportunity should be created 
•	02 – New Lead Object should be created</description>
        <label>Type</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Analytical Staging Object</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Analytical Staging Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Business_Area_New__c</fullName>
        <globalPicklist>Business_Area</globalPicklist>
        <label>Business Area New</label>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OpportunityTeamMember.object
<CustomObject>
    <fields>
        <fullName>Account_Access_Level__c</fullName>
        <globalPicklist>Access_Level</globalPicklist>
        <label>Account Access Level</label>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Case_Access_Level__c</fullName>
        <globalPicklist>Access_Level</globalPicklist>
        <label>Case Access Level</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact_Access_Level__c</fullName>
        <globalPicklist>Access_Level</globalPicklist>
        <label>Contact Access Level</label>
        <required>true</required>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/classes/CreateOppOrLead.cls
global class CreateOppOrLead implements Database.Batchable<sObject>, Database.Stateful {

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            'SELECT Id, Access_Level__c, Account_Access_Level__c, Case_Access_Level__c, ' +
            'Contact_Access_Level__c, Customer_Id__c, Member_Id__c, ' +
            'Name, Number_of_Days__c, Opportunity_Lead_Owner__c, ' + 
            'Status__c, Team_Role__c, Type__c' +
            'FROM Analitical_Staging_Object__c WHERE Status__c = \'New\''
        );
    }

    global void execute(Database.BatchableContext bc, List<Analitical_Staging_Object__c> scope) {
        
        List<Opportunity> opps = new List <Opportunity>();
        List<OpportunityTeamMember> teamMembers = new List<OpportunityTeamMember>();
        List<Task> tasks = new List<Task>();
        List<Lead> leads = new List<Lead>();


        Set<Id> accountsId = new Set<Id>();
        Set<String> emails = new Set<String>();
        for (Analitical_Staging_Object__c a : scope) {
            emails.add(a.Opportunity_Lead_Owner__c);
            accountsId.add(a.Customer_Id__c);
        }

        List<User> users = [SELECT Id, Email FROM User WHERE Email IN :emails];
        Map<String, Id> email2UserId = new Map<String, Id>();
        for (User u : users) {
            if (!email2UserId.containsKey(u.Email)) {
                email2UserId.put(u.Email, u.Id);
            }
        }

        List<Account> accounts = [SELECT Id, OwnerId FROM Account WHERE Id IN :accountsId];
        Map<Id, Id> acc2AccOwnerId = new Map<Id, Id>();
        for (Account a : accounts) {
            acc2AccOwnerId.put(a.Id, a.OwnerId);
        }

        for (Analitical_Staging_Object__c aso : scope) {
            if (aso.Type__c == '01') {
                Id oppOwner;
                
                if (email2UserId.containsKey(aso.Opportunity_Lead_Owner__c)) {
                    oppOwner = email2UserId.get(aso.Opportunity_Lead_Owner__c);
                }else {
                    oppOwner = acc2AccOwnerId.get(aso.Customer_Id__c);
                }

                Opportunity opportunity = new Opportunity( Name = aso.Name, AccountId = aso.Customer_Id__c, OwnerId = oppOwner, Business_Area_New__c = 'Production');
                OpportunityTeamMember teamMember = new OpportunityTeamMember ( UserId = aso.Member_Id__c, TeamMemberRole = aso.Team_Role__c,
                    Account_Access_Level__c = aso.Access_Level__c, Case_Access_Level__c = aso.Case_Access_Level__c, Contact_Access_Level__c = aso.Contact_Access_Level__c, OpportunityId = opportunity.Id
                );
                Task task = new Task ( OwnerId = opportunity.OwnerId, ActivityDate = Date.today().addDays((Integer)aso.Number_of_Days__c), Type = 'AnalyticalOppTask');
                opps.add(opportunity);
                teamMembers.add(teamMember);
                tasks.add(task);
                aso.Status__c = 'OK';
            }else if (aso.Type__c == '02') {

            }else {
                aso.Status__c = 'NOK';
            }
        }

        if (opps.size() > 0) {
            insert opps;
        }
        if (teamMembers.size() > 0) {
            insert teamMembers;
        }
        if (tasks.size() > 0) {
            insert tasks;
        }
    }

    global void finish(Database.BatchableContext bc) {
        
    }    
}  